---
- name: Install PWA / PPSWebApp
  hosts: localhost
  become: True
  gather_facts: no
  roles:
    - install
    - configure
  pre_tasks:
    - include_vars:
        dir: vars/localhost/
#- name: Implement A3S entry to PWA - Grumpy
#  hosts: "*grumpy-app*"
#  become: True
#  gather_facts: no
#  roles:
#    - detector
#  pre_tasks:
#    - include_vars:
#        dir: vars/grumpy/