#!/bin/sh

if [ ! -d {{ATL_base_dir}}/BACKUP/jira ]
then
   mkdir -p {{ATL_base_dir}}/BACKUP/jira
fi

rm {{ATL_base_dir}}/BACKUP/jira/jira_daily_03.tgz
mv {{ATL_base_dir}}/BACKUP/jira/jira_daily_02.tgz {{ATL_base_dir}}/BACKUP/jira/jira_daily_03.tgz
mv {{ATL_base_dir}}/BACKUP/jira/jira_daily_01.tgz {{ATL_base_dir}}/BACKUP/jira/jira_daily_02.tgz

/usr/bin/pg_dump jiradb > /tmp/jiradb.db.dump
mv /tmp/jiradb.db.dump {{ATL_base_dir}}/jira/data/jiradb.db.dump
tar cfz {{ATL_base_dir}}/BACKUP/jira/jira_daily_01.tgz {{ATL_base_dir}}/jira
rm {{ATL_base_dir}}/jira/data/jiradb.db.dump
