---
- hosts: web
  tasks:
  - name: create a web file
    file:
      dest: '{{web_file}}'
      state: '{{file_state}}'

- hosts: backup
  tasks:
  - file:
      dest: '{{backup_file}}'
      state: '{{file_state}}'

- hosts: nodejs
  tasks:
  - file:
      dest: '{{nodejs_file}}'
      state: '{{file_state}}'
    when: nodejs_file is defined
- hosts: all
  tasks:
  - file:
      dest: '{{all_file}}'
      state: '{{file_state}}'
