---
- name: Implement ansibleuser
  hosts: all
  become: yes

  vars:
    user_name: user
  tasks:
  - name: Add a new user ansibleuser
    user:
      name: "{{ user_name }}"
      shell: /bin/bash
      group: wheel
      append: yes

  - name: Set authorized keys from controller machine
    authorized_key:
      user: "{{ user_name }}"
      state: present
      key: "{{ lookup('file', 'id_rsa.pub') }}"

  - name: Add user "ansibleuser" to sudo
    lineinfile:
      path: /etc/sudoers.d/users
      line: '{{ user_name}} ALL=(ALL) NOPASSWD: ALL'
      state: present
      mode: 0440
      create: yes
#      validate: 'visudo -cf %s'

  - name: Set includedir in sudoers
    lineinfile:
      dest: /etc/sudoers
      line: "#includedir /etc/sudoers.d"
      state: present
#      validate: "/usr/sbin/visudo -cf %s"
