- name: Ensure group "readonly" exists
  group:
    name: readonly
    state: present

- name: Add the user "restricteduser"
  user:
    name: restricteduser
    comment: Managed by Ansible.
    uid: 5000
    group: readonly
    shell: /bin/bash

- name: Check /tmp/mc-restricteduser
  stat:
    path: /tmp/mc-restricteduser
  register: mc_restricteduser
  tags:
    - mc_fix

- name: Fix temp folder for mc
  file:
    path: "/tmp/mc-restricteduser"
    state: directory
    owner: restricteduser
    group: readonly
    mode: 0755
  when: mc_restricteduser.stat.exists
  tags:
    - mc_fix

- name: Add authorized keys from "public_keys" folder
  authorized_key:
    user: restricteduser
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "public_keys/*.pub"