- name: Check installed status
  stat:
    path: "/opt/snow/snowagent"
  register: snow_agent_installed

- name: prepare folders for SNOW agent
  file:
    path: "/tmp/SNOW_agent"
    state: directory
    recurse: yes
    mode: 0755
  when: snow_agent_installed.stat.exists == False

- name: Copy SNOW agent package to destination
  copy:
    mode: 0755
    src: wolterskluwer_snowagent-5.0.1-1.x86_64.rpm
    dest: "/tmp/SNOW_agent"
  when: snow_agent_installed.stat.exists == False
  
- name: Install package
  yum:
    name: /apps/SNOW_agent/wolterskluwer_snowagent-5.0.1-1.x86_64.rpm
    state: present
  become: true
  when: snow_agent_installed.stat.exists == False

- name: Copy pre-defined SNOW agent cron configuration
  copy:
    mode: 0755
    src: snowcron.conf
    dest: "/opt/snow/"
  become: true
  when: snow_agent_installed.stat.exists == False

- name: Re-configure cron for SNOW agent.
  shell: ./snowcron -f ./snowcron.conf /opt/snow/snowagent
  args:
    chdir: "/opt/snow/"
    executable: /bin/bash
  become: true
  when: snow_agent_installed.stat.exists == False