- name: Confluence - Check installed status
  stat:
    path: "{{ ATL_confluence_base_dir }}/data/confluence.cfg.xml"
  register: confluence_installed

- name: Confluence - Prepare folder
  file:
    path: "{{ ATL_confluence_base_dir }}/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0640
  with_items: ["", "data"]

- name: Confluence - Unarchive
  unarchive:
    src: "https://www.atlassian.com/software/confluence/downloads/binary/{{ATL_confluence_source_file}}"
    validate_certs: yes
    owner: root
    dest: "{{ ATL_base_dir }}/confluence"
    remote_src: yes
  when: confluence_installed.stat.exists == False

- name: Confluence - Symlink
  file:
    src: "{{ ATL_confluence_base_dir }}/{{ ATL_confluence_untar_folder_name }}"
    dest: "{{ ATL_confluence_base_dir }}/confluence"
    state: link
    force: yes

- name: Confluence - Prepare init-script
  template:
    src: "confluence/confluence.service"
    dest: "/usr/lib/systemd/system/confluence.service"
    mode: 0644
    owner: root
    group: root
  notify:
    - reload systemd
    - autostart confluence
  tags:
    - confluence_conf
    

- name: Confluence - Config adjust <confluence-init.properties>
  template:
    src: "confluence/confluence-init.properties"
    dest: "{{ ATL_confluence_base_dir }}/confluence//confluence/WEB-INF/classes/confluence-init.properties"
  tags:
    - confluence_conf
  notify:
    - restart confluence

- name: Confluence - Config adjust <setenv.sh>
  template:
    src: "confluence/setenv.sh"
    dest: "{{ ATL_confluence_base_dir }}/confluence/bin/setenv.sh"
  tags:
    - confluence_conf
  notify:
    - restart confluence

- name: Confluence - Config adjust <web.xml>
  template:
    src: "confluence/web.xml"
    dest: "{{ ATL_confluence_base_dir }}/confluence//confluence/WEB-INF/web.xml"
  tags:
    - confluence_conf
  notify:
    - restart confluence

- name: Confluence - Config adjust <server.xml>
  template:
    src: "confluence/server.xml"
    dest: "{{ ATL_confluence_base_dir }}/confluence/conf/server.xml"
  tags:
    - confluence_conf
  notify:
    - restart confluence

- name: Confluence - Trigger setup notification!  
  debug:
    msg: "You will get important information as a handler at the end of playbook's run. Please follow it"
  changed_when: "confluence_installed.stat.exists == False"
  notify:
    - finish install confluence