- name: Java - Check installed status
  stat:
    path: "{{ ATL_java_base_dir }}/jdk/release"
  register: java_installed

- name: Java -  Prepare target folder
  file:
    path: "{{ ATL_java_base_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0640

- name: Java - Copy java to remote (&& checksum)
  copy:
    src: "{{ ATL_java_source_file }}"
    dest: "/tmp"
  when: java_installed.stat.exists == False

- name: Java - Unarchive java
  unarchive:
    src: /tmp/{{ ATL_java_source_file }}
    dest: "{{ ATL_base_dir }}/java"
    remote_src: true
  when: java_installed.stat.exists == False

- name: Java - Symlink
  file:
    src: "{{ ATL_java_base_dir }}/{{ ATL_java_untar_folder_name }}"
    dest: "{{ ATL_java_base_dir }}/jdk"
    state: link
    force: yes

- name: Java - Cleanup
  file:
    path: /tmp/{{ ATL_java_source_file }}
    state: absent
