- name: Jira - Check installed status
  stat:
    path: "{{ ATL_jira_base_dir }}/data/dbconfig.xml"
  register: jira_installed

- name: Jira - Prepare folder
  file:
    path: "{{ ATL_jira_base_dir }}/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0640
  with_items: ["", "data"]

- name: Jira - unarchive
  unarchive:
    src: "https://www.atlassian.com/software/jira/downloads/binary/{{ATL_jira_source_file}}"
    validate_certs: yes
    owner: root
    dest: "{{ ATL_base_dir }}/jira"
    remote_src: true
  when: jira_installed.stat.exists == False

- name: Jira - Symlink
  file:
    src: "{{ ATL_jira_base_dir }}/{{ ATL_jira_untar_folder_name }}"
    dest: "{{ ATL_jira_base_dir }}/jira"
    state: link
    force: yes

- name: Jira - Prepare init-script
  template:
    src: "jira/jira.service"
    dest: "/usr/lib/systemd/system/jira.service"
    mode: 0644
    owner: root
    group: root
  notify:
    - reload systemd
    - autostart jira
  tags:
    - jira_conf

- name: Jira - Config adjust <server.xml>
  template:
    src: "jira/server.xml"
    dest: "{{ ATL_jira_base_dir }}/jira/conf/server.xml"
  tags:
    - jira_conf
  notify:
    - restart jira

- name: Jira - Config adjust <setenv.sh>
  template:
    src: "jira/setenv.sh"
    dest: "{{ ATL_jira_base_dir }}/jira/bin/setenv.sh"
  tags:
    - jira_conf
  notify:
    - restart jira

- name: Jira - Config adjust <jira-config.properties>
  template:
    src: "jira/jira-config.properties"
    dest: "{{ ATL_jira_base_dir }}/data/jira-config.properties"
  tags:
    - jira_conf
  notify:
    - restart jira

- name: Jira - Trigger setup notification!
  debug:
    msg: "You will get important information as a handler at the end of playbook's run. Please follow it"
  changed_when: "jira_installed.stat.exists == False"
  notify:
    - finish install jira
