---
- name: install EPEL
  yum:
      name: epel-release
      state: latest

- name: install dependencies
  yum:
      name:
        - python-pip
        - java-1.8.0-openjdk.x86_64
      state: present

- pip:
    name: lxml #Requirement for maven

- name: Prepare folders for ppswebapp
  file:
    path: "/apps/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0750
  with_items: ["ppswebapp"]

- name: Download ppswebapp "{{PPSWEBAPP_VERSION}}"
  maven_artifact:
    version: "{{ PPSWEBAPP_VERSION }}"
    extension: war
    group_id: com.wk
    artifact_id: pwa-web-ui
    repository_url: 'https://nexus.wolterskluwer.io/nexus/service/local/repositories/releases/content/'
    username: maven
    password: maven
    dest: /apps/ppswebapp/"{{PPSWEBAPP_WAR}}"

- name: Copy handler script of PWA.
  copy:
      owner: root
      group: root
      mode: 0755
      src: pwa.sh
      dest: /apps/ppswebapp/
  notify:
    - restart ppswebapp